# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: digiausna
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRESS_USER: postgress
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postresql/data

volumes:
  db:
    driver: local

